import { callGroq } from "../groqClient";

export async function writerAgent(research: string): Promise<string> {
  const prompt = `
You are a professional blog writer.

Write a high-quality, engaging blog post based on the following research notes.

🧠 These research notes were generated by another agent and contain factual, reliable information about a specific topic.

Your task:
- Use the research to craft a blog post without copying it directly.
- DO NOT add made-up facts or hallucinate.
- Keep the structure: a strong introduction, 2–4 informative sections, and a conclusion.
- Use headings for each section.
- Match a helpful, confident, and informative tone.
- Do NOT mention that this came from research or that it's AI-generated.

Here are the research notes:
${research}
`;

  const draft = await callGroq(prompt);
  return draft;
}